name: CI User u35651
mkdir -p ~/.ssh

 Host devcloud
 chmod 600 ~/.ssh/config

 cd HPCKit-code-samples/matrix_mul/
 jobs: matrix_mul 

build:git clone https://github.com/intel/BaseKit-code-samples.git
  cd BaseKit-code-samples/DPC++Compiler/vector-add/
#!/bin/bash
source /opt/intel/inteloneapi/setvars.sh
make clean
make all
#!/bin/bash
source /opt/intel/inteloneapi/setvars.sh
make run
qsub -l nodes=1:gpu:ppn=2 -d . build.c009.sh
watch -n 1 qstat -n -1
qsub -l nodes=1:gpu:ppn=2 -d . run.c009.sh
<script_name>.sh.u35651, which is the job stderr
<script_name>.sh.u35651, which is the job stdout
cat run.sh.u35651
qstat-s batch@v-qscr-nda

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: rm build.sh.*; rm run.sh.*; 
        echo Add other actions to build,
        echo test, and deploy your project.
        qsub -I -l nodes=1:gpu:ppn=2 -d. run.c009.sh
        make all && make run
        build_fpga_emu.sh
#!/bin/bash
source /opt/intel/inteloneapi/setvars.sh
make fpga_emu -f Makefile.fpga
run_fpga_emu.sh
#!/bin/bash
source /opt/intel/inteloneapi/setvars.sh
make run_emu -f Makefile.fpga
qsub -l nodes=1:fpga_compile:ppn=2 -d . build_fpga_emu.sh
qsub -l nodes=1:fpga_compile:ppn=2 -d . run_fpga_emu.sh
build_fpga_hw.sh
#!/bin/bash
source /opt/intel/inteloneapi/setvars.sh
make hw -f Makefile.fpga
run_fpga_hw.sh
#!/bin/bash
source /opt/intel/inteloneapi/setvars.sh
make run_hw -f Makefile.fpga
qsub -l nodes=1:fpga_compile:ppn=2 -d . build_fpga_hw.sh
qsub -l nodes=1:fpga_runtime:ppn=2 -d . run_fpga_hw.sh
        make clean
        exit

